title: "M.B. O'Reilly's site"
description: "The latest news from the world of M.B. O'Reilly."

show_downloads: false
show_github: false

email: "mb@mboreilly.com"
# twitter: "https://twitter.com/mb_oreilly"
# twitter_name: "@mb_oreilly"

twitter:
  username: "mb_oreilly"

author_name: "M.B. O'Reilly"

url: "https://conoreilly.github.io"
baseurl: "/mbwebsite"

google_analytics: "G-BF0XDRL5VB"

plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-feed 



include: ["_pages"]

collections:
 posts: 
  output: true
 books:
  output: true
 poems:
  output: true

github:
  owner_name: "conoreilly"
