description: "This is all the info you need on MB O'Reilly."
email: "mb@mboreilly.com"
twitter: "https://twitter.com/mb_oreilly"
twitter_name: "@mb_oreilly"

collections:
 blogposts:
  output: true
  
