title: "M.B. O'Reilly's site"
description: "This is all the info you need on MB O'Reilly."
email: "mb@mboreilly.com"
twitter: "https://twitter.com/mb_oreilly"
twitter_name: "@mb_oreilly"

url: "https://conoreilly.github.io"
baseurl: "/mbwebsite"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme 


include: ["_pages"]

collections:
 posts:
  output: true
 books:
  output: true
 poems:
  output: true

